name: Deploy
on:
  push:
    branches: master
  pull_request_target:
    branches: master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: export NVM_DIR=~/.nvm &&
          source ~/.nvm/nvm.sh &&
          cd ~/workspace/strapi-music && 
          git pull && 
          pnpm run build && 
          pm2 restart 0
      
